# Generated by Django 4.2 on 2025-08-07 11:57

from django.db import migrations, models
import django.db.models.deletion
import packing_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_order_code', models.CharField(max_length=20)),
                ('production_demand_code', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_po', models.CharField(max_length=50)),
                ('customer_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KitElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_number', models.CharField(max_length=10)),
                ('box_sequence', models.CharField(max_length=10)),
                ('element_desc', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=packing_system.models.kit_image_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packing_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_elements', to='packing_system.packingdata')),
            ],
        ),
    ]
